export const countryOptions = [
    // { label: "Select a country", value: "" },
    { label: "🇦🇫 Afghanistan", value: "AF" },
    { label: "🇦🇱 Albania", value: "AL" },
    { label: "🇩🇿 Algeria", value: "DZ" },
    { label: "🇦🇸 American Samoa", value: "AS" },
    { label: "🇦🇩 Andorra", value: "AD" },
    { label: "🇦🇴 Angola", value: "AO" },
    { label: "🇦🇮 Anguilla", value: "AI" },
    { label: "🇦🇶 Antarctica", value: "AQ" },
    { label: "🇦🇬 Antigua and Barbuda", value: "AG" },
    { label: "🇦🇷 Argentina", value: "AR" },
    { label: "🇦🇲 Armenia", value: "AM" },
    { label: "🇦🇺 Australia", value: "AU" },
    { label: "🇦🇹 Austria", value: "AT" },
    { label: "🇦🇿 Azerbaijan", value: "AZ" },
    { label: "🇧🇸 Bahamas", value: "BS" },
    { label: "🇧🇭 Bahrain", value: "BH" },
    { label: "🇧🇩 Bangladesh", value: "BD" },
    { label: "🇧🇧 Barbados", value: "BB" },
    { label: "🇧🇾 Belarus", value: "BY" },
    { label: "🇧🇪 Belgium", value: "BE" },
    { label: "🇧🇿 Belize", value: "BZ" },
    { label: "🇧🇯 Benin", value: "BJ" },
    { label: "🇧🇹 Bhutan", value: "BT" },
    { label: "🇧🇴 Bolivia", value: "BO" },
    { label: "🇧🇦 Bosnia and Herzegovina", value: "BA" },
    { label: "🇧🇼 Botswana", value: "BW" },
    { label: "🇧🇷 Brazil", value: "BR" },
    { label: "🇧🇳 Brunei", value: "BN" },
    { label: "🇧🇬 Bulgaria", value: "BG" },
    { label: "🇧🇫 Burkina Faso", value: "BF" },
    { label: "🇧🇮 Burundi", value: "BI" },
    { label: "🇰🇭 Cambodia", value: "KH" },
    { label: "🇨🇲 Cameroon", value: "CM" },
    { label: "🇨🇦 Canada", value: "CA" },
    { label: "🇨🇻 Cape Verde", value: "CV" },
    { label: "🇨🇫 Central African Republic", value: "CF" },
    { label: "🇹🇩 Chad", value: "TD" },
    { label: "🇨🇱 Chile", value: "CL" },
    { label: "🇨🇳 China", value: "CN" },
    { label: "🇨🇴 Colombia", value: "CO" },
    { label: "🇰🇲 Comoros", value: "KM" },
    { label: "🇨🇬 Congo", value: "CG" },
    { label: "🇨🇩 Congo, The Democratic Republic of the", value: "CD" },
    { label: "🇨🇷 Costa Rica", value: "CR" },
    { label: "🇭🇷 Croatia", value: "HR" },
    { label: "🇨🇺 Cuba", value: "CU" },
    { label: "🇨🇾 Cyprus", value: "CY" },
    { label: "🇨🇿 Czech Republic", value: "CZ" },
    { label: "🇩🇰 Denmark", value: "DK" },
    { label: "🇩🇯 Djibouti", value: "DJ" },
    { label: "🇩🇲 Dominica", value: "DM" },
    { label: "🇩🇴 Dominican Republic", value: "DO" },
    { label: "🇪🇨 Ecuador", value: "EC" },
    { label: "🇪🇬 Egypt", value: "EG" },
    { label: "🇸🇻 El Salvador", value: "SV" },
    { label: "🇬🇶 Equatorial Guinea", value: "GQ" },
    { label: "🇪🇷 Eritrea", value: "ER" },
    { label: "🇪🇪 Estonia", value: "EE" },
    { label: "🇪🇹 Ethiopia", value: "ET" },
    { label: "🇫🇯 Fiji", value: "FJ" },
    { label: "🇫🇮 Finland", value: "FI" },
    { label: "🇫🇷 France", value: "FR" },
    { label: "🇬🇦 Gabon", value: "GA" },
    { label: "🇬🇲 Gambia", value: "GM" },
    { label: "🇬🇪 Georgia", value: "GE" },
    { label: "🇩🇪 Germany", value: "DE" },
    { label: "🇬🇭 Ghana", value: "GH" },
    { label: "🇬🇷 Greece", value: "GR" },
    { label: "🇬🇩 Grenada", value: "GD" },
    { label: "🇬🇺 Guam", value: "GU" },
    { label: "🇬🇹 Guatemala", value: "GT" },
    { label: "🇬🇳 Guinea", value: "GN" },
    { label: "🇬🇼 Guinea-Bissau", value: "GW" },
    { label: "🇬🇾 Guyana", value: "GY" },
    { label: "🇭🇹 Haiti", value: "HT" },
    { label: "🇭🇳 Honduras", value: "HN" },
    { label: "🇭🇰 Hong Kong", value: "HK" },
    { label: "🇭🇺 Hungary", value: "HU" },
    { label: "🇮🇸 Iceland", value: "IS" },
    { label: "🇮🇳 India", value: "IN" },
    { label: "🇮🇩 Indonesia", value: "ID" },
    { label: "🇮🇷 Iran", value: "IR" },
    { label: "🇮🇶 Iraq", value: "IQ" },
    { label: "🇮🇪 Ireland", value: "IE" },
    { label: "🇮🇱 Israel", value: "IL" },
    { label: "🇮🇹 Italy", value: "IT" },
    { label: "🇯🇲 Jamaica", value: "JM" },
    { label: "🇯🇵 Japan", value: "JP" },
    { label: "🇯🇴 Jordan", value: "JO" },
    { label: "🇰🇿 Kazakhstan", value: "KZ" },
    { label: "🇰🇪 Kenya", value: "KE" },
    { label: "🇰🇼 Kuwait", value: "KW" },
    { label: "🇱🇧 Lebanon", value: "LB" },
    { label: "🇱🇮 Liechtenstein", value: "LI" },
    { label: "🇱🇺 Luxembourg", value: "LU" },
    { label: "🇲🇴 Macau", value: "MO" },
    { label: "🇲🇰 North Macedonia", value: "MK" },
    { label: "🇲🇬 Madagascar", value: "MG" },
    { label: "🇲🇼 Malawi", value: "MW" },
    { label: "🇲🇾 Malaysia", value: "MY" },
    { label: "🇲🇻 Maldives", value: "MV" },
    { label: "🇲🇱 Mali", value: "ML" },
    { label: "🇲🇹 Malta", value: "MT" },
    { label: "🇲🇦 Morocco", value: "MA" },
    { label: "🇲🇽 Mexico", value: "MX" },
    { label: "🇲🇳 Mongolia", value: "MN" },
    { label: "🇲🇪 Montenegro", value: "ME" },
    { label: "🇲🇿 Mozambique", value: "MZ" },
    { label: "🇳🇵 Nepal", value: "NP" },
    { label: "🇳🇱 Netherlands", value: "NL" },
    { label: "🇳🇿 New Zealand", value: "NZ" },
    { label: "🇳🇬 Nigeria", value: "NG" },
    { label: "🇳🇴 Norway", value: "NO" },
    { label: "🇴🇲 Oman", value: "OM" },
    { label: "🇵🇰 Pakistan", value: "PK" },
    { label: "🇵🇸 Palestine", value: "PS" },
    { label: "🇵🇦 Panama", value: "PA" },
    { label: "🇵🇪 Peru", value: "PE" },
    { label: "🇵🇭 Philippines", value: "PH" },
    { label: "🇵🇱 Poland", value: "PL" },
    { label: "🇵🇹 Portugal", value: "PT" },
    { label: "🇶🇦 Qatar", value: "QA" },
    { label: "🇷🇴 Romania", value: "RO" },
    { label: "🇷🇺 Russia", value: "RU" },
    { label: "🇸🇦 Saudi Arabia", value: "SA" },
    { label: "🇸🇳 Senegal", value: "SN" },
    { label: "🇷🇸 Serbia", value: "RS" },
    { label: "🇸🇬 Singapore", value: "SG" },
    { label: "🇸🇰 Slovakia", value: "SK" },
    { label: "🇸🇮 Slovenia", value: "SI" },
    { label: "🇿🇦 South Africa", value: "ZA" },
    { label: "🇰🇷 South Korea", value: "KR" },
    { label: "🇪🇸 Spain", value: "ES" },
    { label: "🇱🇰 Sri Lanka", value: "LK" },
    { label: "🇸🇩 Sudan", value: "SD" },
    { label: "🇸🇪 Sweden", value: "SE" },
    { label: "🇨🇭 Switzerland", value: "CH" },
    { label: "🇸🇾 Syria", value: "SY" },
    { label: "🇹🇼 Taiwan", value: "TW" },
    { label: "🇹🇿 Tanzania", value: "TZ" },
    { label: "🇹🇭 Thailand", value: "TH" },
    { label: "🇹🇳 Tunisia", value: "TN" },
    { label: "🇹🇷 Turkey", value: "TR" },
    { label: "🇺🇬 Uganda", value: "UG" },
    { label: "🇺🇦 Ukraine", value: "UA" },
    { label: "🇦🇪 United Arab Emirates", value: "AE" },
    { label: "🇬🇧 United Kingdom", value: "UK" },
    { label: "🇺🇸 United States", value: "US" },
    { label: "🇺🇾 Uruguay", value: "UY" },
    { label: "🇺🇿 Uzbekistan", value: "UZ" },
    { label: "🇻🇪 Venezuela", value: "VE" },
    { label: "🇻🇳 Vietnam", value: "VN" },
    { label: "🇾🇪 Yemen", value: "YE" },
    { label: "🇿🇲 Zambia", value: "ZM" },
    { label: "🇿🇼 Zimbabwe", value: "ZW" },
];
